# Generated by Django 4.2.6 on 2023-10-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_user_alter_patient_doctors_person_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
